### PR TITLE
Update landscape.yml with Riverbed logo

### PR DESCRIPTION
**Pull request by amenasiddiqi**
Added Riverbed to the Observability & Analysis - Monitoring subcategory.

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [ ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~5 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by amenasiddiqi** [comment]
Need to upload riverbed.svg to hosted_logos dierctory. Help?

**Comment by dankohn** [comment]
You need to upload the SVG. Please also replace https://www.riverbed.com/appinternals/ with the URL it redirects to.

**Comment by amenasiddiqi** [comment]
Hi Dan,

I don’t have push rights to the hosted_logos directory. Logo attached. Can you help?

Will update the URL.

Amena

**Comment by dankohn** [comment]
You need to add the logo to your fork of the repo. Or, you can zip the SVG and attach it to this issue via the GitHub web interface.

**Comment by amenasiddiqi** [comment]
[riverbed.svg.zip](https://github.com/cncf/landscape/files/2989883/riverbed.svg.zip)
Here's the logo. 
And here's the corrected URL: https://www.riverbed.com/products/steelcentral/steelcentral-appinternals.html

**Comment by dankohn** [comment]
Could you please try making the upload yourself here: https://github.com/amenasiddiqi/landscape/tree/patch-1/hosted_logos

If it doesn't work, I can do it manually.

**Comment by amenasiddiqi** [comment]
Done

**Comment by dankohn** [comment]
You got it. There was one more error which I think I just fixed. We'll see if it builds now.

**Comment by dankohn** [comment]
Your submission is correct but we need to move things around to make space for it. We'll get it working in a day or so.

**Comment by amenasiddiqi** [comment]
Thanks, Dan!

**Pull request closed without merging**
