### PR TITLE
Update repo_url AppScale

### PR DESCRIPTION
**Pull request by NicolasDenutte**
Forgot to add repo_url of AppScale in previous pull request (AppScale is open source). Sorry about this oversight.

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source?
* [ ] If it is open source, does your project have at least 250 GitHub stars?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ ] Are you including an SVG or (less preferably) a large PNG?
* [ ] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] Does your project/product name match the text on the logo?
* [ ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] 2 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by NicolasDenutte** [comment]
[https://s3.amazonaws.com/appscale_CDN/images/Appscale-logo.svg](url)

@dankohn quick question: would the 'original' AppScale logo (see link) work with the white background for open source projects or would it still conflict?

**Comment by dankohn** [comment]
@NicolasDenutte please see:
https://github.com/cncf/landscape#logos
>4. Don't use reversed logos (i.e., with a non-white, non-transparent background color). If you only have a reversed logo, create an issue with it attached and we'll produce a non-reversed version for you.

However, if you have a different non-reversed logo you'd like to use, you're welcome to.

**Comment by NicolasDenutte** [comment]
@dankohn Ok, unfortunately we don't have a better one at the moment so the current non-reversed logo is good. Thanks for helping us out with that.

**Comment by dankohn** [comment]
Our pleasure.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Pull request merged**
