### PR TITLE
Add alibaba cloud function compute to serverless hosted platform

### PR DESCRIPTION
**Pull request by nerdyyatrice**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [ ] Have you picked the single best (existing) category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ ] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [ ] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] Does your project/product name match the text on the logo?
* [ ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] 2 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by dankohn** [comment]
Please use a version of the SVG that says "Alibaba Cloud Function Compute" underneath, or we can add that for you if you want.

https://deploy-preview-654--landscape.netlify.com/grouping=organization&organization=alibaba-cloud&selected=alibaba-cloud-function-compute

**Comment by dankohn** [comment]
@alexcontini Please modify this logo to include the words "Alibaba Cloud Function Compute" underneath. You can open a new branch with the info, or paste a zipped version here. Thanks.

**Comment by alexcontini** [comment]
@dankohn here is the revised logo:

[alibaba-cloud-function-compute.svg.zip](https://github.com/cncf/landscape/files/2045048/alibaba-cloud-function-compute.svg.zip)

**Comment by dankohn** [comment]
Closed with ba3b51feaf47a98d8c91c636a561a85dbfc10c33

**Comment by nerdyyatrice** [comment]
Thank you very much Dan!

**Pull request closed without merging**
