### PR TITLE
Added Citrix ADM in Monitoring tools

### PR DESCRIPTION
**Pull request by bhardwajk**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~5 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by bhardwajk** [comment]
LGTM

**Comment by dankohn** [comment]
We're happy to move https://landscape.cncf.io/selected=citrix-adc-formerly-net-scaler-adc from Service Proxy to Monitoring. However, could you please open a new PR that deletes the old entry, creates the new one, and also points to a working Twitter feed.

**Comment by bhardwajk** [comment]
@dankohn - Citrix ADC and Citrix ADM are two different products though closely linked. Citrix ADC is a service proxy, Citrix ADM is the analytics & monitoring tool.

**Comment by dankohn** [comment]
Unfortunately, we have a rule of one product per company. https://github.com/cncf/landscape#new-entries

Could you please decide which one you'd like to feature.

**Pull request closed without merging**
