### PR TITLE
Updated LeanIX products

### PR DESCRIPTION
**Pull request by dominikrose-leanix**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~15 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by caniszczyk** [comment]
@dominikrose-leanix please pick one product/project in the same category

**Comment by dominikrose-leanix** [comment]
@caniszczyk They are two different products, is it ok like this?

**Comment by caniszczyk** [comment]
"We generally will only list a company's product in one box, to represent its major or best-known offering. We occasionally make exceptions for large companies. Note that if we allowed listing the same product or project in multiple boxes, the over 600 logos on the landscape would multiply to many times that many."

https://github.com/cncf/landscape#new-entries

**Comment by caniszczyk** [comment]
please resubmit the PR and put one product, honestly what you have probably belongs in the obs/monitoring section

**Pull request closed without merging**
