### PR TITLE
Change existing Sysdig OSS and add Sysdig Secure

### PR DESCRIPTION
**Pull request by bencer**
Change URL and rename logo for existing Sysdig entry
Add a new entry for Sysdig Secure

### CODE REVIEW

**Comment by dankohn** [comment]
Sorry, but this seems to go against this guideline:

https://github.com/cncf/landscape#new-entries
"We are generally not including commercial versions of open source software. The exception is that we are showing all Certified Kubernetes implementations."

**Comment by bencer** [comment]
Hi @dankohn,

Sysdig Secure is not a commercial version of open source project. Its a different product with much wider scope: image scanning, compliance, runtime security and forensics.

The same parallelism can be found already in the Landscape:

- Weave Cloud (in the landscape) uses flux, weave and possible others (included in the landscape)
- Aqua (again in the landscape) uses kube-bench (also in the landscape)

Can we please reconsider this? Thanks! :)

**Comment by dankohn** [comment]
We can reconsider but I remain unclear on the difference between the OSS Sysdig and Sysdig Secure. If we include them both, the logos need to differentiate the offerings.

**Comment by bencer** [comment]
OSS Sysdig is a Linux (with container support) troubleshooting tool.
Sysdig Secure: container security product

and including Falco for completeness:

Falco: open source project for intrusion and abnormality detection

The descriptions, taken from landscape page:

OSS Sysdig: Observability and Analysis > Monitoring: Linux system exploration and troubleshooting tool with first class support for containers (logo: spade on a red circle with Sysdig letters)

Sysdig Secure: Sysdig Secure provides container security for Kubernetes and Cloud-Native apps including vulnerability management and image scanning, compliance and audit, runtime security, threat defense and forensics. Sysdig Secure is built on top of the Falco project is part of Sysdig Cloud-Native visibility and security platform. (logo: blue/white spade with Sysdig letters)

Falco: Provisioning : Security & Compliance: Container Native Runtime Security (logo: Falcon)

**Comment by dankohn** [comment]
OK. Would it be possible to distinguish between OSS Sysdig and Sysdig Secure using text in the logos, please?

**Pull request closed without merging**
