### PR TITLE
Add CloudWeGo to Landscape

### PR DESCRIPTION
**Pull request by GuangmingLuo**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you added your SVG to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~15 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by GuangmingLuo** [comment]
LGTM

**Comment by GuangmingLuo** [comment]
@caniszczyk  please take a look

**Comment by caniszczyk** [comment]
@GuangmingLuo I don't see the logo?

**Comment by GuangmingLuo** [comment]
> @GuangmingLuo I don't see the logo?

It is in the area of "Remote Procedure Call", please take another look.

**Comment by GuangmingLuo** [comment]
LGTM  
Hi @caniszczyk Chirs，please take a look, thank you

**Comment by GuangmingLuo** [comment]
I have updated the svg image. @caniszczyk Please take a look and leave a message if something is wrong or unsatisfied.

**Pull request merged**
