### PR TITLE
Add OPEA to CNAI landscape.yml under new sub-category of Open Enterprise AI Blueprints

### PR DESCRIPTION
**Pull request by chickenrae**
Ref: https://github.com/cncf/landscape/issues/4170

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [ ] Have you picked the single best (existing) category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ ] Have you added your SVG to `hosted_logos` and referenced it there?
* [ ] Does your logo clearly state the name of the project/product and follow the other [guidelines](https://github.com/cncf/landscape#new-entries)?
* [ ] Does your project/product name match the text on the logo?
* [ ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?

Signed-off-by: Rachel Roumeliotis <rroumeliotis@gmail.com>

### CODE REVIEW

**Comment by castrojo** [comment]
OK landed this for expediency. I'll keep an eye on the incoming PRs from now until the 11th if you have follow on fixes that you need, cheers!

**Comment by arun-gupta** [comment]
When is the visual representation at https://landscape.cncf.io/?group=cnai&view-mode=grid get updated?

**Comment by chickenrae** [comment]
I see it sometimes...weirdly 
Screenshot 2024-12-07 at 11 31 05 AM

**Comment by arun-gupta** [comment]
This is what I see, probably will make its way through CDN
image

**Pull request merged**
