### PR TITLE
Update graduated status

### PR DESCRIPTION
**Pull request by craigbox**
Graduate Istio to the graduated list on https://www.cncf.io/projects/.

### CODE REVIEW

**Comment by craigbox** [comment]
...did you mean to do this?

**Comment by castrojo** [comment]
Looks like it was autoclosed when the one ahead of you was merged:

https://github.com/cncf/landscape/pull/3324

I don't think I've ever seen this behavior before in github?!

**Comment by craigbox** [comment]
Maybe we both used the same branch name?  I'm not sure why I wasn't merging into `main` by default.
There was another small fix in this one, I'll recreate it.

**Comment by craigbox** [comment]
How is https://www.cncf.io/projects/ updated btw?

**Comment by castrojo** [comment]
I can confirm it's on there now (cron job runs twice a day).

**Pull request closed without merging**
