### PR TITLE
Add Gloo to the landscape

### PR DESCRIPTION
**Pull request by ilevine**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source?
* [x] If it is open source, does your project have at least 250 GitHub stars?
* [ ] Have you picked the single best category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Are you including an SVG or (less preferably) a large PNG?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] 2 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by dankohn** [comment]
Nice submission. You need to pick one category though for the project.

Also, I love the logo, but do you have it in SVG or AI format, as that's higher-res and smaller.

**Comment by ilevine** [comment]
the purpose of gloo is to "glue" the 2 landscape so it is playing in them both ... any suggestion ?

**Comment by dankohn** [comment]
I recommend https://landscape.cncf.io/grouping=no&landscape=service-management along with the other API gateways. But your choice.

**Comment by dankohn** [comment]
Ping. Could you please update the PR?

**Comment by dankohn** [comment]
I'm closing this for now, but please reopen as soon as you have answers and an SVG and we'll be happy to merge.

**Pull request closed without merging**
