### PR TITLE
Added NuoDB to Databases

### PR DESCRIPTION
**Pull request by SkellyNuo**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [X] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
-- Closed source - linked to GitHub organization

* [X] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
-- Not open source

* [X] Have you picked the single best (existing) category for your project?
-- Database

* [X] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?

* [X] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
-- Added to Hosted Logos

* [X] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?

* [X] Does your project/product name match the text on the logo?

* [X] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?

* [ ] ~5 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by dankohn** [comment]
Implemented here: https://landscape.cncf.io/selected=nuo-db

Let me know if you need any changes.

**Comment by SkellyNuo** [comment]
Hi Dan,

Thanks for helping with this! The profile itself looks good.

Curious if you could remove the "-" between nuo and db in the URL path to
make it =nuodb. We keep it one word. Let me know if thats possible.

Thank you!

[image: Screen Shot 2019-06-19 at 9.39.25 AM.png]


Samantha Kelly
Digital Marketing Manager

www.nuodb.com
p: +1 617 500 0001

c: +1 857 323 1295

t: @nuodb <https://twitter.com/nuodb>

l: linkedin.com/company/NUODB <https://www.linkedin.com/company/nuodb>



The information contained in this email is confidential and proprietary and
intended for the sole use of the intended recipient. If the reader of this
message is not the intended recipient, you are hereby notified that any
dissemination, distribution or copying of this communication is strictly
prohibited. If you have received this email in error, please notify the
sender and delete all copies.

**Comment by dankohn** [comment]
You're welcome. Sorry, can't help with the hyphen. We're using
https://www.npmjs.com/package/param-case which sets it that way
automatically.
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by SkellyNuo** [comment]
Ok. No worries! Good to go then.

Thank you



Samantha Kelly
Digital Marketing Manager

www.nuodb.com
p: +1 617 500 0001

c: +1 857 323 1295

t: @nuodb <https://twitter.com/nuodb>

l: linkedin.com/company/NUODB <https://www.linkedin.com/company/nuodb>



The information contained in this email is confidential and proprietary and
intended for the sole use of the intended recipient. If the reader of this
message is not the intended recipient, you are hereby notified that any
dissemination, distribution or copying of this communication is strictly
prohibited. If you have received this email in error, please notify the
sender and delete all copies.

**Pull request closed without merging**
