### PR TITLE
Adding LIMA as an installer 

### PR DESCRIPTION
**Pull request by Rania-Bojar**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~15 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Review by Rania-Bojar — COMMENTED** [review]
LGTM

**Comment by Rania-Bojar** [comment]
Hallo everybody,

Can you please tell me if there is anythying else we can do to merge this request? 

Thank you in advance
Rania.B

**Review by Rania-Bojar — COMMENTED** [review]
LGTM

**Comment by caniszczyk** [comment]
@ErinThacker @amye can you confirm that LIMA signed paperwork via https://github.com/cncf/k8s-conformance/pull/1383

**Comment by ErinThacker** [comment]
@caniszczyk @amye - working on this under PR #1170

**Comment by Rania-Bojar** [comment]
Thank you everyone for your Time and effort! we hope to see LIMA soon on the Landscape :)

**Pull request merged**
