### PR TITLE
Adding apache airflow

### PR DESCRIPTION
**Pull request by John151**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you added your SVG to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other [guidelines](https://github.com/cncf/landscape#new-entries)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?

### CODE REVIEW

**Comment by castrojo** [comment]
Ready to go we just need the DCO thing to pass.

**Comment by omid** [comment]
Just asking, is Apache Airflow cloud native?

**Comment by John151** [comment]
Airflow provides the workflow management capabilities that are integral to modern cloud-native data platforms.

**Comment by omid** [comment]
@John151 thanks. Sorry that I asked and brought this topic here. I randomly saw your PR and had this question in my mind.
@castrojo is there a solid border to accept apps? AFAIK "cloud native" doesn't have a strict meaning! So do you accept a PHP or BASH server/service also? Can you lead me to some definition?

**Pull request closed without merging**
