### PR TITLE
Argo summary

### PR DESCRIPTION
**Pull request by AndreyKozlov1984**
This is an update for an Argo PR with a fixed issue on line 4440
Original PR is here - https://github.com/cncf/landscape/pull/2911

### CODE REVIEW

**Comment by AndreyKozlov1984** [comment]
@wojtekidd please review!

**Comment by AndreyKozlov1984** [comment]
https://deploy-preview-2925--landscape.netlify.app/summary

**Comment by CathPag** [comment]
LGTM! Thanks for your help, @AndreyKozlov1984!

**Comment by wojtekidd** [comment]
Thank you 👍

**Pull request merged**
