### PR TITLE
Adding KubeCarrier project to the landscape

### PR DESCRIPTION
**Pull request by KrissiWi**
Hi there,

we'd like to add our open source project KubeCarrier to the landscape. 

I am aware we are still below the threshold of 300 stars but we get quite some interest for the project and think it is very future oriented: KubeCarrier provides a central framework utilizing Kubernetes Operators and APIs, allowing users to deliver cloud-native service management from one multi-cloud, multi-cluster hub. To us, automating the application layer is the necessary next step of the cloud native journey. 

More information on the project in here: 
https://www.infoq.com/news/2020/10/kubermatic-announces-kubecarrier/

Looking forward to your feedback. (Uploading the svg now) 

Cheers,

Kristin

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~15 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by KrissiWi** [comment]
@taylorwaggoner : Seems like uploads to `Hosted_Logos` is disabled. Adding the SVG here.

**Comment by taylorwaggoner** [comment]
@KrissiWi the issue is probably that your entry to the landscape.yml shows the logo as "logo: kubercarrier.svg".  If you fix the file name, it should be okay.  Please upload the image to Hosted Logos.  thanks!

**Comment by KrissiWi** [comment]
Hi @taylorwaggoner,

I just tried with the renamed file but keep getting this error message when clicking on upload file

image

**Comment by taylorwaggoner** [comment]
@KrissiWi are you trying to upload the logo to your branch or directly to master?  Feel free to send the logo to me at twaggoner@linuxfoundation.org or attach here and I'll give it a shot. Thanks!

**Comment by KrissiWi** [comment]
@taylorwaggoner : Thank you very much for the support. Here is the link to the SVG: 

https://drive.google.com/file/d/1Q34ZSrXgOhu7I2RVFbwnZIAMRnmLXCnl/view?usp=sharing

I added the png as well in case this is off help.

KubeCarrier (1)

Thanks again for the support!

Kristin

**Comment by taylorwaggoner** [comment]
@KrissiWi I opened a new pull request for this https://github.com/cncf/landscape/pull/1895
Thanks!

**Pull request closed without merging**
