### PR TITLE
Update StormForger to StormForge

### PR DESCRIPTION
**Pull request by qedrakmar**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [ ] Have you picked the single best (existing) category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~15 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by qedrakmar** [comment]
> Have you picked the single best (existing) category for your project?

We would also like to discuss a new subcategory, in the existing Observability and Analysis category, but that is secondary to this update.  What is the best way to approach that conversation?

**Comment by caniszczyk** [comment]
re: new sub category, create an issue here: https://github.com/cncf/landscape/issues

what's the diff between stormforger and stormforge? it's not obvious visiting the sites

**Comment by qedrakmar** [comment]
This reflects an acquisition and rebrand.  StormForger was acquired by Carbon Relay, and the whole platform is now StormForge.  (Member cards and logos were recently updated, but we missed the landscape card.)

**Comment by caniszczyk** [comment]
thanks @qedrakmar for the explanation

**Comment by caniszczyk** [comment]
@qedrakmar file a new issue regarding a new subcategory, happy to explore!

**Pull request merged**
