### PR TITLE
fix: project jupyter repo_url hyperlink

### PR DESCRIPTION
**Pull request by rahulmansharamani14**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you added your SVG to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other [guidelines](https://github.com/cncf/landscape#new-entries)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?

This solves #4137

### CODE REVIEW

**Comment by rahulmansharamani14** [comment]
@lukaszgryglicki It seems this PR is still not merged as it says 2 workflows awaiting approval. Do I suppose to do something?

**Comment by lukaszgryglicki** [comment]
waiting for validate landscape.yaml. No action on your side IMHO.

**Comment by rahulmansharamani14** [comment]
> waiting for validate landscape.yaml. No action on your side IMHO.

Okay. Just wanted to let you know it is showing "This workflow is awaiting approval from a maintainer in https://github.com/cncf/landscape/pull/4156" (attaching ss). Maybe if you rerun the workflow or let it be!

Screenshot 2024-11-25 at 2 33 06 AM

**Comment by rahulmansharamani14** [comment]
Thank you @lukaszgryglicki!

**Pull request merged**
