### PR TITLE
First implementation of embed=true. close #400

### LINKED ISSUE #400: Add card-only version for iframe embedding
We want to be able to embed the landscape in an iframe. When `embed=yes` please don't display the header or the filter bar. Just show the cards and the footer.

Here's an example of an embed:

https://www.dankohn.com/test

### PR DESCRIPTION
**Pull request by ZeusTheTrueGod**
Need to test this first, for example on jsfiddle.

### CODE REVIEW

**Comment by ZeusTheTrueGod** [comment]
https://deploy-preview-461--landscape.netlify.com/embed.html

**Comment by ZeusTheTrueGod** [comment]
So I don't see an easy way how to properly show a popup here.

**Comment by dankohn** [comment]
This already works fairly well. The remaining issue is to have the modal pop up in the middle of the view window rather than in the middle of the iFrame.

Please note my extra 2 commits.

Also, we want to change the footer to show a large: "[View](https://landscape.cncf.io/grouping=landscape&landscape=special) the full interactive landscape." and have it open in a new tab to the same view.

**Comment by ZeusTheTrueGod** [comment]
@dankohn now I open a selected item in a new tab when a popup is in a mobile style: i.e. the page is too narrow or it is being run on mobile.

**Comment by ZeusTheTrueGod** [comment]
Regarding the `View the full interactive landscape.`, can it be outside the iframe ?

**Comment by ZeusTheTrueGod** [comment]
Can we merge this ?

**Pull request merged**
