### PR TITLE
942 detect redirects

### PR DESCRIPTION
**Pull request by ZeusTheTrueGod**
```
{ homepageUrl: 'https://servicecomb.incubator.apache.org/',
  type: 'redirect',
  location: 'http://servicecomb.apache.org/' }
{ homepageUrl: 'https://www.ghostcloud.cn/products/list/1.html',
  type: 'error',
  message:
   'net::ERR_TIMED_OUT at https://www.ghostcloud.cn/products/list/1.html' }
{ repo_url: 'https://github.com/supergiant/supergiant',
  type: 'redirect',
  location: 'https://github.com/supergiant/control' }
{ repo_url: 'https://github.com/cloud66/habitus',
  type: 'redirect',
  location: 'https://github.com/cloud66-oss/habitus' }
{ repo_url:
   'https://github.com/apache/incubator-servicecomb-java-chassis',
  type: 'redirect',
  location: 'https://github.com/apache/servicecomb-java-chassis' }
{ repo_url: 'https://github.com/kubernetes/helm',
  type: 'redirect',
  location: 'https://github.com/helm/helm' }
{ repo_url: 'https://github.com/apache/incubator-pulsar',
  type: 'redirect',
  location: 'https://github.com/apache/pulsar' }
{ repo_url: 'https://github.com/coreos/etcd',
  type: 'redirect',
  location: 'https://github.com/etcd-io/etcd' }
{ repo_url: 'https://github.com/kubernetes-incubator/cri-o',
  type: 'redirect',
  location: 'https://github.com/kubernetes-sigs/cri-o' }
{ repo_url: 'https://github.com/alibaba/dragonfly',
  type: 'redirect',
  location: 'https://github.com/dragonflyoss/Dragonfly' }
error Command failed with exit code 1.
```

### CODE REVIEW

**Comment by ZeusTheTrueGod** [comment]
Is this a good format for you ?

**Comment by dankohn** [comment]
Please just return a `.` on 200.

**Comment by ZeusTheTrueGod** [comment]
Yep, the output is for invalid / redirected entries

**Comment by ZeusTheTrueGod** [comment]
Overall, now it looks good to me

**Comment by dankohn** [comment]
Please switch back to the style of messages you had before instead of JSON.

**Comment by ZeusTheTrueGod** [comment]
LGTM

**Pull request merged**
