### PR TITLE
Add Edge Delta under observability

### PR DESCRIPTION
**Pull request by davereese**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [X] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [X] Have you picked the single best (existing) category for your project?
* [X] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [X] Have you added your SVG to `hosted_logos` and referenced it there?
* [X] Does your logo clearly state the name of the project/product and follow the other [guidelines](https://github.com/cncf/landscape#new-entries)?
* [X] Does your project/product name match the text on the logo?
* [X] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?

### CODE REVIEW

**Comment by castrojo** [comment]
The logo seems to have extra padding, is that correct?

**Comment by davereese** [comment]
> The logo seems to have extra padding, is that correct?

It shouldn't. I believe it just looks that way in the diff.

**Comment by cynthia-sg** [comment]
Cloud you please add viewBox or height/width to the svg? Without the viewBox tag and without any width or height specified, the svg won't scale.

**Comment by castrojo** [comment]
Thanks everyone, looking snazzy!

**Pull request merged**
