### PR TITLE
Update Giant Swarm logo for CNCF cloud native landscape

### PR DESCRIPTION
**Pull request by marians**
This PR edits existing entries for Giant Swarm, with the purpose to update Giant Swarm's logo for the CNCF landscape.

The existing logo has a very wide shape, which makes it very much unreadable in the CNCF cloud native landscape [print/PDF version](https://landscape.cncf.io/images/landscape.pdf), where each logo has to fit a square container.

We upload a logo variation to the `hosted_logos` folder which is better suited for this purpose. (Source: https://raw.githubusercontent.com/giantswarm/brand/v1.0.0/logo/special-purpose/cncf-landscape-stacked.svg)

We also remove the deprecated version of the logo from the `hosted_logos` and `cached_logos` folder.

However we do not remove `cached_logos/giant-swarm-member.svg`, since we don't know the purpose of that one.

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~15 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by marians** [comment]
According to the preview https://deploy-preview-1827--landscape.netlify.app/format=members this hasn't changed the logo in the members directory yet. But as a first step, the result looks good to me.

**Comment by marians** [comment]
LGTM

**Comment by dankohn** [comment]
Please update all the instances to use the new logo: https://deploy-preview-1827--landscape.netlify.app/format=card-mode&organization=giant-swarm

**Comment by marians** [comment]
@dankohn Thanks for the hunch. So I have now also modified `processed_landscape.yaml`. It's a bit hard to understand which occurrence does what. I hope it's fine.

**Pull request merged**
