### PR TITLE
Update landscape with YRCloudFile

### PR DESCRIPTION
**Pull request by wpf710**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~5 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by wpf710** [comment]
LGTM

**Comment by dankohn** [comment]
We ask that the text in the logo match the product name. So, could you please either switch to a logo that says `YRCloudFile`, or we can change the product name to `YanRong`, or we can add the text `YRCloudFile` underneath your existing logo. Please let us know which you prefer.

**Comment by dankohn** [comment]
We created this logo for you: https://deploy-preview-1163--landscape.netlify.com/category=cloud-native-storage&format=card-mode&grouping=category&selected=yr-cloud-file

If it looks OK could you please reply with an LGTM.

**Comment by dankohn** [comment]
Ping? Please confirm I should merge. Otherwise, I will close the issue unmerged, but I can merge in the future if you confirm this is correct.

**Comment by wpf710** [comment]
LGTM

**Comment by wpf710** [comment]
sorry for the late response

**Comment by wpf710** [comment]
@dankohn Thanks

**Pull request merged**
