### PR TITLE
Update landscape.yml

### PR DESCRIPTION
**Pull request by wu-sheng**
- Change the url of project
- Change project name, add `Apache prefix`
- Add twitter url.

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source?
* [x] If it is open source, does your project have at least 250 GitHub stars?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Are you including an SVG or (less preferably) a large PNG?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] 2 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by wu-sheng** [comment]
LGTM

**Comment by dankohn** [comment]
Thanks for the very good PR. We're following the policy:

https://github.com/cncf/landscape#logos
>6. Match the item name to the English words in the logos. So an Acme Rocket logo that shows "Rocket" should have product name "Rocket", while if the logo shows "Acme Rocket", the product name should be "Acme Rocket". Otherwise, logos looks out of place when you sort alphabetically.

You can see that we're consistent in that here: https://landscape.cncf.io/grouping=organization&organization=apache-software-foundation

Do you have a new Skywalking logo that includes `Apache` in it? Or would you like us to make one for you?

Twitter and homepage changes are fine, of course.

**Comment by wu-sheng** [comment]
Thanks for sharing your policy. Make sense. I will revert the name change, because we used this logo in our product UI, and Apache hold the trademark, it can't be simply changed by me or others without Apache Foundation permission. :)

**Comment by dankohn** [comment]
LGTM. Just a note that you will improve your Google results if you can set skywalking.org to hard redirect (301) to skywalking.io.

**Comment by wu-sheng** [comment]
@dankohn For this month, we are holding `skywalking.org` and `skywalking.io` at the same time. But still thanks for reminding me.

**Pull request merged**
