### PR TITLE
DO NOT MERGE 799 andrey category refactor

### PR DESCRIPTION
**Pull request by ZeusTheTrueGod**
#799 + #514 : big picture for new categories

@dankohn please review the changes in the layout.

### CODE REVIEW

**Comment by Vanuan** [comment]
It looks like there was a bad merge:

https://github.com/cncf/landscape/pull/800/commits/1d6bd940a30e13a5e808b413a246194a115b8a18

I don't see other explanation for deleting numerous items.

**Comment by dankohn** [comment]
Here's the explanation: https://github.com/cncf/landscape/issues/807

Please open a pull request to add anything back, if it gets new commits.

**Comment by Vanuan** [comment]
Why I need to readd stuff that shouldn't have been removed in the first place? There's clearly some bug if this removal process is automated.

**Comment by Vanuan** [comment]
Even if I readd it, where's the guarantee it won't be removed again after some faulty script is ran?

**Pull request merged**
