### PR TITLE
Update sysdig oss listing: name, logo, description.

### PR DESCRIPTION
**Pull request by bencer**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [ ] Have you picked the single best (existing) category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ ] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [ ] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] Does your project/product name match the text on the logo?
* [ ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~5 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by dankohn** [comment]
We've already switched to the new Sysdig logo but you're trying to switch back to an older one.

Logo on https://sysdig.com/opensource/ is https://478h5m1yrfsa3bbe262u7muv-wpengine.netdna-ssl.com/wp-content/uploads/2019/10/sysdig-logo.svg.

Cc @kris-nova

**Comment by bencer** [comment]
@dankohn we are in the process of updating the website /opensource. The logo that was recently updated is the company logo. This "old logo" is our sysdig OSS project logo moving forward.
We hope that with the different logo there is a more clear distinction between Sysdig company and sysdig OSS project.

More background here: https://sysdig.com/blog/understanding-common-library-implementation/

**Comment by dankohn** [comment]
Separate logos for open source and company are great. 

Unfortunately, we have the [rule](https://github.com/cncf/landscape#new-entries) "We generally will only list a company's product in one box, to represent its major or best-known offering. We occasionally make exceptions for large companies." So, you need to limit Sysdig to *1* closed source product, plus the member card, plus an unlimited number of open source offerings (though each must have at least 300 stars).

**Comment by bencer** [comment]
I was hoping to make 2 separated PRs, one with this update on the OSS, I'll do one in the future with the closed source products update.

**Comment by dankohn** [comment]
That's fine. Please LGTM if this looks OK.

**Comment by dankohn** [comment]
You've updated both the member and the project logo: https://deploy-preview-1467--landscape.netlify.com/format=card-mode&grouping=organization&organization=sysdig

Don't you want them to be different?

**Comment by bencer** [comment]
good catch, we should be good now! thanks!

**Comment by kris-nova** [comment]
Thanks all!

**Pull request merged**
