### PR TITLE
Add Reduxio to CNCF landscape

### PR DESCRIPTION
**Pull request by rmoshe**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~5 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by dankohn** [comment]
Please note that https://reduxio.com/ gives a certificate error. I highly recommend getting https://reduxio.com/ to redirect to https://www.reduxio.com/. In the meantime, I'll manually change your submission.

**Comment by rmoshe** [comment]
@dankohn - Thank you for that !
Cheers !

**Comment by rmoshe** [comment]
@dankohn - The proccess states to comment LGTM once we are ready to merge.
We did not comment LGTM as we did not want the PR merged yet.

We found some incompatibilities in Crunchbase we need to resolve prior to merge.

Could you please the operation so Reduxio will not show on master ?

Once we are ready we will comment LGTM .
Thanks

**Comment by dankohn** [comment]
OK, reverted.

**Comment by rmoshe** [comment]
@dankohn - Thank you for your quick reply and taking action !
Once we are ready should we create a new PR or comment LGTM on this one ?

**Comment by dankohn** [comment]
Either way.
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Pull request merged**
