### PR TITLE
Update runner.svg

### PR DESCRIPTION
**Pull request by lukebabb**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source?
* [x] If it is open source, does your project have at least 250 GitHub stars?
* [x] Have you picked the single best category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Are you including an SVG?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] 2 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by lukebabb** [comment]
LGTM

**Comment by dankohn** [comment]
Thanks for the PR. I did it manually as new logos need to go in `hosted_logos`.

**Comment by lukebabb** [comment]
Thank you. An oversight on my part, thanks for the update!

**Comment by tnir** [comment]
@lukebabb Thanks for the update. On my Firefox browser (Fx 61.0a1 on macOS 10.13), I saw your logo SVG is something wrong...
https://landscape.cncf.io/selected=git-lab-runner
gitlab-runner-on-landscape

cc @dankohn

Note: https://landscape.cncf.io/selected=git-lab does not have a similar problem.

**Comment by tnir** [comment]
@dankohn Thanks for confirming 🙇 It looks fine too with 62.0a1 (2018-06-13). I'm sorry for confusing you.

**Pull request closed without merging**
