### PR TITLE
add KubeStellar to CNCF landscape based on sandbox admission 12-19-2023

### PR DESCRIPTION
**Pull request by clubanderson**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you added your SVG to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~30 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by clubanderson** [comment]
What am I doing wrong?

**Comment by clubanderson** [comment]
@Cmierly can you advise me on what I am doing wrong in this PR to cause a failure?

**Comment by castrojo** [comment]
I don't have access to the logs but asked an admin, here's the error: 

```The issue: 7:56:11 PM: FATAL: No cached entry, and KubeStellar has issues with logo: kubestellar.svg, SVG file embeds a png. Please use a pure svg file```

**Comment by clubanderson** [comment]
> I don't have access to the logs but asked an admin, here's the error:
> 
> `The issue: 7:56:11 PM: FATAL: No cached entry, and KubeStellar has issues with logo: kubestellar.svg, SVG file embeds a png. Please use a pure svg file`

Thank you, I have updated with a different version of the SVG.  I hope this one is native.

**Comment by amye** [comment]
Sweet, @castrojo - this will help us out with one missing project!

**Comment by clubanderson** [comment]
@castrojo @amye ready for merge

**Comment by castrojo** [comment]
Alright, thanks for your patience on that svg thing, let's gooooooo!

**Comment by clubanderson** [comment]
@castrojo when should we expect to see the output on landscape.cncf.io?

**Pull request merged**
