### PR TITLE
Add Sumo Logic to monitoring

### PR DESCRIPTION
**Pull request by frankreno**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~5 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by dankohn** [comment]
We're happy to move you from Logging to Monitoring but you can only be in one section: https://landscape.cncf.io/grouping=no&selected=sumo-logic

**Comment by frankreno** [comment]
@dankohn oh really? Interesting, ok we do both logging and monitoring.  So we cannot be listed in both sections?

**Comment by dankohn** [comment]
Yes, unfortunately, if we allowed that, we would go from 600 logos to thousands.

https://github.com/cncf/landscape#new-entries
"Put the project in the single category where it best fits."

Shall I move you to monitoring?

**Comment by frankreno** [comment]
will close, we will stay in the logging space for the moment.  As a feature request for this site, it would be great to support multiple locations primarily for clarity.  From a user perspective, this makes it look like we don't support monitoring.  but then if we move to monitoring, it looks like we don't support logging so introduces some confusion.

**Pull request closed without merging**
