### PR TITLE
Add Kubewarden to landscape

### PR DESCRIPTION
**Pull request by flavio**
Kubewarden is a CNCF sandbox project. It has been added to sandbox during last July.

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [X] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [X] Have you picked the single best (existing) category for your project?
* [X] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [X] Have you added your SVG to `hosted_logos` and referenced it there?
* [X] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [X] Does your project/product name match the text on the logo?
* [X] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~30 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by flavio** [comment]
The first run of the netlify bot failed because I forgot to add the `kubewarden.svg` to the PR :sweat: 

This is now addressed, I don't know how to trigger netlify bot again

**Comment by flavio** [comment]
ping, can someone please look it that?

**Comment by caniszczyk** [comment]
@AndreyKozlov1984 can you fix this one up?

**Comment by caniszczyk** [comment]
this is now solved via https://github.com/cncf/landscape/pull/2801 (finally)

**Comment by flavio** [comment]
@caniszczyk: thanks!

**Pull request closed without merging**
