### PR TITLE
Add DEEP Framework

### PR DESCRIPTION
**Pull request by eistrati**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] 2 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by eistrati** [comment]
Will provide SVG format in the next day or two.

**Comment by eistrati** [comment]
Looks like an issue with `deploy/netlify`. Correct URL is https://raw.githubusercontent.com/MitocGroup/deep-framework/master/docs/logo.svg (instead of https://raw.githubusercontent.com/MitocGroup/deep-framework/raw/master/docs/logo.svg)

**Comment by dankohn** [comment]
https://github.com/MitocGroup/deep-framework/master/docs/logo.svg does not load for me.

**Comment by eistrati** [comment]
Changed with raw github url - https://raw.githubusercontent.com/MitocGroup/deep-framework/master/docs/logo.svg

**Comment by dankohn** [comment]
@ZeusTheTrueGod Could you please look at why this SVG is getting incorrectly cropped?

**Comment by ZeusTheTrueGod** [comment]
@dankohn that is not an SVG. that is a png inserted in an svg. Just click the link, https://raw.githubusercontent.com/MitocGroup/deep-framework/master/docs/logo.svg

**Comment by eistrati** [comment]
@ZeusTheTrueGot @dankohn I apologize on behalf of our team. We are working to fix this issue. Will provide shortly updated SVG.

**Comment by eistrati** [comment]
@ZeusTheTrueGod @dankohn We have updated above logo - https://github.com/MitocGroup/deep-framework/pull/637 . Please review current pull request and let me know if you see any other issues with it. Thanks in advance!

**Pull request merged**
