### PR TITLE
make a section header clickable in a landscape / serverless modes. close #945

### LINKED ISSUE #945: Clicking on categories in should take you to that category
On the regular and serverless landscape, clicking on a subcategory header takes you to the card view of that subcategory. The same should happen when you click on a category header.

### PR DESCRIPTION
**Pull request by ZeusTheTrueGod**

### CODE REVIEW

**Comment by dankohn** [comment]
Clicking `Provisioning` from the regular landscape should take you to https://deploy-preview-946--landscape.netlify.com/grouping=landscape&landscape=provisioning not to https://deploy-preview-946--landscape.netlify.com/landscape=provisioning.

**Comment by ZeusTheTrueGod** [comment]
We don't have the rule to change grouping to the landscape when you click on a category or a subcategory header in the big picture. Should I add it?

**Comment by dankohn** [comment]
Thanks for raising. Yes, clicking on `Database` in the landscape should take you to https://landscape.cncf.io/grouping=landscape&landscape=database not to https://landscape.cncf.io/landscape=database as it does now.

**Comment by dankohn** [comment]
Can you please finish this?

**Comment by ZeusTheTrueGod** [comment]
@dankohn , LGTM

**Pull request merged**
