### PR TITLE
add k6

### PR DESCRIPTION
**Pull request by simskij**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~15 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

--- 

I totally get that you'd like to avoid creating new categories. I think it suits well under Observability and Analysis, but the current subcategories don't really match, hence the new subcategory.

If you have any better suggestions, feel free to let me know and I'll edit it right away, but given there is no testing category at all (neither top level nor sublevel) I would argue that it would make sense to create one.

### CODE REVIEW

**Comment by simskij** [comment]
LGTM

**Comment by caniszczyk** [comment]
please don't create a new sub-category and put it under somewhere that already exists

**Comment by simskij** [comment]
Ok, so given that k6 is already part of the cdf landscape, I'll go ahead and move it to the CI&D category. Thanks again.

**Comment by simskij** [comment]
LGTM

**Pull request merged**
