### PR TITLE
Web landscape web landscape 2023 01 20 t18 40

### PR DESCRIPTION
**Pull request by ColinSullivan1**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you added your SVG to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~30 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by gcolliso** [comment]
lgtm

**Comment by gcolliso** [comment]
receiving random error when trying to create preview - `Build started
Processing the tree
FATAL: item NATS cannot have project_org and additional_repos set simultaneously
Can not report fatal errors, REPOSITORY_URL not provided`

Not sure what fix is needed. Please advise.

**Comment by caniszczyk** [comment]
@AndreyKozlov1984 can you figure out what's going on here and resolve the PR?

**Comment by AndreyKozlov1984** [comment]
@ColinSullivan1 we allow only project_org or additional_reps, not both. I think in your case additional_reps is enough, please confirm and I'll edit the PR

**Comment by gcolliso** [comment]
@AndreyKozlov1984 That is fine just to use the additional repos then. Thanks. cc/ @ColinSullivan1

**Comment by AndreyKozlov1984** [comment]
@gcolliso does it look fine? Then I could merge it.

**Comment by gcolliso** [comment]
lgtm - thanks @AndreyKozlov1984

**Pull request merged**
