### PR TITLE
Replace the TiDB logo

### PR DESCRIPTION
**Pull request by queenypingcap**
The TiDB logo was outdated. So I replaced it with the latest one.

### CODE REVIEW

**Comment by dankohn** [comment]
Thanks for this, but we got this (more professional) logo from the TiDB team in China: 6e0806dfb6c35b37a421701a2c8381ae2fffa6f1

**Comment by queenypingcap** [comment]
Thanks, Dan. This is Queeny from PingCAP. I filed this PR because the previous logo 
 on [CNCF Cloud Native Interactive Landscape](https://landscape.cncf.io/) was outdated. The new logo you uploaded works for us.

**Comment by dankohn** [comment]
OK. I think this logo looks great: https://landscape.cncf.io/grouping=landscape&landscape=database-and-data-warehouse&selected=ti-db

**Comment by queenypingcap** [comment]
Yes, it does. Thanks a lot!

**Pull request closed without merging**
