### PR TITLE
Rebrand Loodse to Kubermatic

### PR DESCRIPTION
**Pull request by KrissiWi**
Hi there,

- Loodse (company) has been rebranded to Kubermatic.

- Kubermatic (product) has been rebranded to Kubermatic Kubernetes Platform

- The new company logo in SVG format: https://drive.google.com/file/d/1fjcMAU_J20FJu-5OUJCgPPeYEA_yCfRw/view?usp=sharing

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [NA ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ NA] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [NA] Have you picked the single best (existing) category for your project?
* [ NA] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ NA] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [ NA] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [NA ] Does your project/product name match the text on the logo?
* [ x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~15 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by KrissiWi** [comment]
I just realized the product logo needs updating as well: https://drive.google.com/file/d/1Y73nNAI4qkLA3bbf6mmLN7hagjd2Z3s_/view?usp=sharing

**Comment by dankohn** [comment]
Could you please add to your pull request and then LGTM again.

**Pull request merged**
