### PR TITLE
504 andrey fix yarn fetch

### PR DESCRIPTION
**Pull request by ZeusTheTrueGod**
This fixes the algorithm - images are looked not only by the logo, but also by the item name. Thus we don't have problems when multiple items have the same logo.

### CODE REVIEW

**Comment by dankohn** [comment]
In your PR, cached_logos/alauda-kcsp.svg is corrupted because it has an extra return above the xml declaration.

**Comment by dankohn** [comment]
Also cached_logos/alauda-ee.svg is corrupted.

**Comment by dankohn** [comment]
There's also some strange cropping going on, like with LinuxKit: https://github.com/cncf/landscape/pull/516/files?short_path=bd99803#diff-bd99803f71ab299a8e28b7f1806c5a70

**Comment by ZeusTheTrueGod** [comment]
It is not corrupted, just github  can not display it, but browser displays everything. Anyway, I've removed an empty line.

**Comment by ZeusTheTrueGod** [comment]
Linux kit actually looks ok , it is a github viewer which display is improperly. I've opened it in a new tab and tried to change the browser size, the image was adjusted properly

**Pull request merged**
