### PR TITLE
Add meshery to landscape

### PR DESCRIPTION
**Pull request by Aisuko**
Signed-off-by: Aisuko <urakiny@gmail.com>

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* x ] ~5 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by dankohn** [comment]
No trailing slash, please

**Comment by dankohn** [comment]
We need a version of the logo with a transparent background.

**Comment by dankohn** [comment]
Detailed rules: https://github.com/cncf/landscape#logos

**Comment by Aisuko** [comment]
Oh, sorry about that. I think what its saying is “If you have an all-white logo, use a transparent background”. I will change to the white background

**Comment by Aisuko** [comment]
@dankohn Please kindly check the logo.Thanks a lot.

**Comment by kushthedude** [comment]
> @dankohn Please kindly check the logo.Thanks a lot.

@Aisuko Trailing slash is there in URL.

**Comment by Aisuko** [comment]
Done

**Comment by kushthedude** [comment]
LGTM

**Comment by leecalcote** [comment]
Looking good, gents. Thank you.

**Comment by Aisuko** [comment]
@dankohn Sorry to bother you, sir. Please take a look at the PR.  I believe it was ready to be merge.

**Comment by leecalcote** [comment]
@dankohn If I can be of assistance on this PR, please task me. A version of the Meshery logo with transparent background has been supplied now. I _think_ we're good to go here.

**Comment by dankohn** [comment]
Apologies for the delay.

**Pull request merged**
