### PR TITLE
add STACKIT Kubernetes Engine (SKE) to the list of Certified Kubernetes - Hosted list

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [ ] Have you picked the single best (existing) category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~15 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by caniszczyk** [comment]
@ErinThacker @amye are these folks actually certified? folks shouldn't be submitted PRs to the certified list and they should be coming from us

**Comment by ErinThacker** [comment]
I think they jumped the gun because I have been too slow for them. I’ll take care of it this morning.
Erin

**Comment by dirien** [comment]
Oh @ErinThacker  and @caniszczyk, sorry for that. I thought we need to make also for changes in the landscape repo also an PR for you folks to review and approve. Especially for the description field we wanted to provide the right input.

Sorry, in no terms we did want to jump any guns  😄 (nice proverb, btw)

Thanks again for the good work you are doing! We definitely appreciate this.

**Comment by dirien** [comment]
@caniszczyk, i checked the README again under New Entries. I could not see that should not create a PR if its about the hosted k8s services. Sorry if i missed something or broke the process. 😢

**Comment by amye** [comment]
No worries, I will take care of you @dirien! 
You're on my list for this today.:)

**Comment by dirien** [comment]
Link to the other PR  https://github.com/cncf/landscape/pull/2103

**Comment by dirien** [comment]
Hi @amye, any updates? Did you had a chance to review the PR?

**Comment by amye** [comment]
Resolved with #2103

**Pull request closed without merging**
