### PR TITLE
update Trivy

### PR DESCRIPTION
**Pull request by itaysk**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you added your SVG to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other [guidelines](https://github.com/cncf/landscape#new-entries)?
* [x] Does your project/product name match the text on the logo?
* [ ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?

### CODE REVIEW

**Comment by itaysk** [comment]
sure, I didn't realize it's required for an oss project. re-added

**Review by mounicarajput — APPROVED** [review]

**Comment by caniszczyk** [comment]
this is old, resubmit

**Comment by itaysk** [comment]
Hi @caniszczyk , can you please clarify what's the issue here? we would like to update the Trivy logo. I believe I followed through all the change requests

**Comment by caniszczyk** [comment]
@itaysk send a new PR, sorry I was closing out a lot of older PRs

**Pull request closed without merging**
