### PR TITLE
Add more wasm projects

### PR DESCRIPTION
**Pull request by nilslice**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you added your SVG to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~30 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by nilslice** [comment]
I noticed the extism logo had an embedded `<image>` tag, so that's been removed. the modsurfer.svg has embedded png's, but i'll need to address that later.

**Comment by alabulei1** [comment]
Hi @nilslice 

Thank you for adding these information! Could please fix the DCO problem? You need to sign off your commit message.

**Comment by nilslice** [comment]
@alabulei1 - oops! just fixed -- thank you

**Comment by nilslice** [comment]
I'm not sure why the logos include some detail outside the intended crop.. will investigate. e.g this presentation of the file includes the ellipse used to create an effect on the logo, but the file in the "Files changed" looks correct.

image

**Pull request merged**
