### PR TITLE
better sort for today/yesterday/etc, close #274

### LINKED ISSUE #274: Sort last commit by human date
Changing this request:

For both last commit and last release, please label all items from the last 7 days as `this week` and sort alphabetically, bucket all items from the previous 7 days as `last week` and sort alphabetically, continuing for `last month`, `2 months ago`.

### PR DESCRIPTION
**Pull request by ZeusTheTrueGod**
I adjust dates first, I get the relative date:
  - anything what happened within last day, is treated as today
  - anything what happened earlier, is converted to '3 days ago'
  - earlier than a week - original date is used
Next, I apply parse the relative date, thus aligning all the dates. Latest commits earlier than a day ago are sorted by original dates.

### CODE REVIEW

**Comment by dankohn** [comment]
This isn't working yet. Look at the bottom of:
https://deploy-preview-435--landscape.netlify.com/grouping=no&license=open-source&sort=latest-commit

What I'm looking for is that all the today's will be sorted in alphabetical
order, preceded by the yesterdays in alphabetical order, then the 2 days
ago, etc.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by ZeusTheTrueGod** [comment]
Starting from Ansible, it is all sorted by name, and Ansible has a latest commit 'yesterday'
What is wrong ?
image

**Comment by ZeusTheTrueGod** [comment]
And before that there are sorted entries which have a latest commit equal to 3 days ago, then 4 days ago

**Comment by dankohn** [comment]
Yugabyte and etcd both show as 3 days ago, so etcd should come first.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by dankohn** [comment]
As we discussed on Slack, please sort alphabetically in buckets of this week, last week, 2 weeks ago, 3 weeks ago, last month, 2 months ago.

**Comment by dankohn** [comment]
Please see the revised version of this request: https://github.com/cncf/landscape/issues/274

**Comment by ZeusTheTrueGod** [comment]
@dankohn please review!

**Pull request merged**
