### PR TITLE
Update Backstage to incubating

### PR DESCRIPTION
**Pull request by caniszczyk**
There are enough votes for this to pass, announcement coming soon!

Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [ ] Have you picked the single best (existing) category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ ] Have you added your SVG to `hosted_logos` and referenced it there?
* [ ] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] Does your project/product name match the text on the logo?
* [ ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~15 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by caniszczyk** [comment]
@AndreyKozlov1984 any idea what's up here?

**Comment by AndreyKozlov1984** [comment]
I need to update borders here, ``` Incubating is out of bound```

**Comment by caniszczyk** [comment]
@AndreyKozlov1984 can you fix the conflicts?

**Comment by AndreyKozlov1984** [comment]
please check how it looks now.

**Comment by caniszczyk** [comment]
@AndreyKozlov1984 can you update this to resolve conflicting files etc

**Comment by AndreyKozlov1984** [comment]
Ok, waiting for a build to finish

**Comment by AndreyKozlov1984** [comment]
Oops, I need to adjust bounds first!

**Comment by AndreyKozlov1984** [comment]
@caniszczyk done

**Pull request merged**
