### PR TITLE
Adding ORAS

### PR DESCRIPTION
**Pull request by bridgetkromhout**
Signed-off-by: Bridget Kromhout <bridget@kromhout.org>

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you added your SVG to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~15 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
> No cached entry, and ORAS has issues with logo: oras.svg, SVG file embeds a png. Please use a pure svg file

I thought I followed the directions to correct this, but I must have missed a step. Will revisit.

Meanwhile, I don't think I'm able to correct these:

> Empty twitter for Plural (member): https://twitter.com/plural_sh
> No cached entry, and Dave (supporter) has issues with twitter: https://twitter.com/davesavesyou, 404 - {"errors":[{"code":34,"message":"Sorry, that page does not exist."}]}
> Empty twitter for OpenGitOps: https://twitter.com/opengitops
> Empty twitter for Spotinst Functions: https://twitter.com/spot_hq

**Comment by amye** [comment]
> > No cached entry, and ORAS has issues with logo: oras.svg, SVG file embeds a png. Please use a pure svg file
> 
> I thought I followed the directions to correct this, but I must have missed a step. Will revisit.
> 
> Meanwhile, I don't think I'm able to correct these:
> 
> > Empty twitter for Plural (member): https://twitter.com/plural_sh
> > No cached entry, and Dave (supporter) has issues with twitter: https://twitter.com/davesavesyou, 404 - {"errors":[{"code":34,"message":"Sorry, that page does not exist."}]}
> > Empty twitter for OpenGitOps: https://twitter.com/opengitops
> > Empty twitter for Spotinst Functions: https://twitter.com/spot_hq

If we can get the ORAS.svg to be 'more right', those errors will go away.

**Comment by bridgetkromhout** [comment]
@amye seems that the new file still has `href="data:image/png;base64` which is probably what this check doesn't like.

**Comment by caniszczyk** [comment]
@bridgetkromhout yep we need a real SVG

**Comment by bridgetkromhout** [comment]
@caniszczyk Thanks. I do not have a "real" SVG; all I have is a PNG (and I'm told that's all that exists in terms of source material). Based on https://github.com/cncf/wp-svg-autocrop#how-can-i-get-a-valid-svg I think I am going to need to request that someone competent in graphics (not me) generate a valid SVG; thanks.

**Comment by caniszczyk** [comment]
@bridgetkromhout we have a design on staff that can help, @amye can you ping Alex to create the necessary images for ORAS :)?

**Comment by amye** [comment]
> @bridgetkromhout we have a design on staff that can help, @amye can you ping Alex to create the necessary images for ORAS :)?

Already in progress :)

**Comment by amye** [comment]
That fixed it.

**Comment by bridgetkromhout** [comment]
LGTM

**Pull request merged**
