### PR TITLE
Add Eclipse Che

### PR DESCRIPTION
**Pull request by sunix**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~15 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by sunix** [comment]
LGTM

**Comment by caniszczyk** [comment]
@sunix I'm not sure this the right category for Che, what's your justification :)?

I think it may make sense to create a new category around "Cloud Native IDEs" that includes Che, GitPod, CodeSpaces etc

**Comment by sunix** [comment]
@caniszczyk 
Sure it may make sense to add a new category.

On another hand, Che is quite different then GitPod or CodeSpaces. Think of Che like
-  a Tekton that you can interact with, live edit the code.
-  a way to preview the futur app in containers without having to rebuild the container itself.

GitPod or CodeSpaces are more Cloud IDE in the sense that these ones run in the Cloud but there is nothing special to help into building Cloud Native apps.

I let you see what you think about that. But yes at first I also had that feeling a category was missing.

**Comment by sunix** [comment]
@caniszczyk any thoughts?

**Comment by sunix** [comment]
ping @caniszczyk ?

**Comment by sunix** [comment]
Hello @caniszczyk 
Could we move forward for this?
cc @dankohn

**Comment by sunix** [comment]
Hello guys, @caniszczyk, @dankohn and @taylorwaggoner
Any thought or update about this PR? It has been a while now. I hope we could move forward.
Thanks!

**Review by shivaylamba — APPROVED** [review]

**Comment by sunix** [comment]
LGTM

**Pull request merged**
