### PR TITLE
[WIP] Update Wasm landscape

### PR DESCRIPTION
**Pull request by alabulei1**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ ] Have you added your SVG to `hosted_logos` and referenced it there?
* [ ] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] Does your project/product name match the text on the logo?
* [ ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~30 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by alabulei1** [comment]
Hi, @caniszczyk and @juntao,

Could you please help review the content? There're still some build issues that cause the CI to fail. I'll try to fix them this week. But the content is All here. Thanks.

**Comment by castrojo** [comment]
Ok I think I fixed the syntax issue, I'm not sure why all the other logos get updated?

**Comment by juntao** [comment]
> Ok I think I fixed the syntax issue, I'm not sure why all the other logos get updated?

Thanks @castrojo 

It seems that the `allow_duplicate_repo` key needs to be at the same level with `item`, but it is now under `extra`. See

https://github.com/cncf/landscape/blob/68ac2f36fde55c2b44d2423d711a7bcae40262de/landscape.yml#L2588C15-L2588C35

That has caused the CI to fail as it cannot pick up the duplicated repos:

https://app.netlify.com/sites/landscape/deploys/64d4fbfeedd88a0008bb7643#L535-L542

Can you amend those? Thanks.

For the SVG images in your commit: I guess you have updated local images? In any case, they look good.

**Comment by alabulei1** [comment]
Hi  @castrojo , Thank you so much!

I have fixed the duplicate repo errors. But I still [met some errors](https://app.netlify.com/sites/landscape/deploys/64d5a5d8641d7100086009f3#L1255-L1281). Can you help me take a look? Thanks.

```
11:16:20 AM: TypeError: Cannot read properties of undefined (reading 'map')
11:16:20 AM:     at /opt/repo/packageRemote/src/components/LandscapeContentRenderer.js:27:50
11:16:20 AM:     at Array.map (<anonymous>)
11:16:20 AM:     at module.exports.render (/opt/repo/packageRemote/src/components/LandscapeContentRenderer.js:18:47)
11:16:20 AM:     at main (/opt/repo/packageRemote/tools/renderItems.js:57:55)
11:16:20 AM: Node.js v18.3.0
11:16:20 AM: build failed Error: Remote build failed
11:16:20 AM:     at makeRemoteBuildWithCache (/opt/build/repo/netlify/landscape.js:254:11)
11:16:20 AM:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
11:16:20 AM:     at async Promise.all (index 0)
11:16:20 AM:     at async main (/opt/build/repo/netlify/landscape.js:301:3)
11:16:20 AM: ​
11:16:20 AM: build.command failed                                        
11:16:20 AM: ────────────────────────────────────────────────────────────────
11:16:20 AM: ​
11:16:20 AM:   Error message
11:16:20 AM:   Command failed with exit code 1: (wget --no-check-certificate --no-cache https://raw.githubusercontent.com/cncf/landscapeapp/master/netlify/landscape.js) && node landscape.js (https://ntl.fyi/exit-code-1)
11:16:20 AM: ​
11:16:20 AM:   Error location
11:16:20 AM:   In build.command from netlify.toml:
11:16:20 AM:   (wget --no-check-certificate --no-cache https://raw.githubusercontent.com/cncf/landscapeapp/master/netlify/landscape.js) && node landscape.js
11:16:20 AM: ​
```

**Comment by alabulei1** [comment]
Here is the issue that might have caused the CI failure. The CI says “FATAL: Project Capsule has been added to sandbox category but does not belong to CNCF”. I have not touched that part of the landscape.yml in this PR, and Project Capsule *is* part of CNCF sandbox. 

https://app.netlify.com/sites/landscape/deploys/64d5a5d8641d7100086009f3#L661-L664

cc @caniszczyk and @juntao

**Comment by caniszczyk** [comment]
we took this PR and merged it via https://github.com/cncf/landscape/pull/3424

can we now work on finalizing the wasm landscape with additional smaller PRs now

We have some small design fixes to do etc

**Comment by alabulei1** [comment]
Thank you! @caniszczyk 

I will work on updating logos and make the design better via small PRs.

**Pull request closed without merging**
