### PR TITLE
added D2iQ Dispatch to CICD section

### PR DESCRIPTION
**Pull request by masonse**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~15 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by masonse** [comment]
@caniszczyk Can you take a look at the failed landscape preview build?

**Comment by dankohn** [comment]
Your logo needs to include the word `Dispatch` as explained in rule 5: https://github.com/cncf/landscape#logos

You can use this if you want:

[d2iq-dispatch.svg.zip](https://github.com/cncf/landscape/files/4843712/d2iq-dispatch.svg.zip)

**Comment by masonse** [comment]
> Your logo needs to include the word `Dispatch` as explained in rule 5: https://github.com/cncf/landscape#logos
> 
> You can use this if you want:
> 
> [d2iq-dispatch.svg.zip](https://github.com/cncf/landscape/files/4843712/d2iq-dispatch.svg.zip)

@dankohn Thanks, Using that svg you suggested.  How can I re-trigger the build?

**Comment by masonse** [comment]
LGTM

**Pull request merged**
