### PR TITLE
Update Red Hat logos #1896

### PR DESCRIPTION
**Pull request by mahithamadhira**
Issue #1896 
Issue URL: https://github.com/cncf/landscape/issues/1896

I have updated the Red Hat Logos which are provided.

### CODE REVIEW

**Comment by nebelfeld** [comment]
Lkkllljjj

CNCF AutoUpdater <notifications@github.com> schrieb am Mo., 25. Jan. 2021,
12:15:

**Comment by caniszczyk** [comment]
hrmm, I don't think this is the official logo

**Comment by caniszczyk** [comment]
Thanks for the contribution but this isn't the Openshift logo (checked with Red Hat representatives)

**Comment by caniszczyk** [comment]
I caught up with Red Hat, they informed me that it is indeed the new logo, thank you!

**Pull request merged**
