### PR TITLE
Add architect to tools section of serverless landscape

### PR DESCRIPTION
**Pull request by kborchers**
Architect is a serverless provisioning and deployment tool at the JS Foundation. More info at https://arc.codes

### CODE REVIEW

**Comment by krook** [comment]
I also added this to the Tools tab of [the spreadsheet](https://docs.google.com/spreadsheets/d/10rSQ8rMhYDgf_ib3n6kfzwEuoE88qr0amUPRxKbwVCk/edit#gid=0):

**Comment by levbogusiewicz** [comment]
I added Architect to Tools in the yml. [https://248-lev-add-arc-to-tools--interactive-landscape.netlify.com/grouping=landscape](url)

**Comment by dankohn** [comment]
Resolved: https://landscape.cncf.io/selected=architect

**Comment by kborchers** [comment]
Thanks!

**Pull request closed without merging**
