### PR TITLE
Adding EnterpriseDB as database

### PR DESCRIPTION
**Pull request by bhavanirao**
I would like to add EnterpriseDB to the landscape under databases because we are cloud native, support K8s. I can't import my SVG file to the repo hosted_logos. Can someone help me upload the file, the error message I get when uploading is that i don't have push permissions.

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [ ] Have you picked the single best (existing) category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ ] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [ ] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] Does your project/product name match the text on the logo?
* [ ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~5 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by dankohn** [comment]
You’re probably trying to attach it to master instead of your fork. But feel free to zip the svg and attach it here.

**Comment by dankohn** [comment]
Unfortunately. This entry would go against: “We are generally not including commercial versions of open source software. The exception is that we are showing all Certified Kubernetes implementations.”

https://github.com/cncf/landscape/blob/master/README.md#new-entries

**Comment by bhavanirao** [comment]
I don't understand. Percona, Vertica, MongoDB are all offer commericial versions of open source software

**Comment by dankohn** [comment]
I spent some time researching this, as we're trying to apply the rules in a fair and neutral way. The rule specifically prohibits commercial versions of open source software. When the core open source software is owned by a commercial entity, as with Oracle MySQL, MongoDB, or Hashicorp Nomad, that is allowed.

We're treating Percona as an open source fork of MySQL, as with MariaDB. They have commercial backing, but they also have GitHub repos with substantially different software than what they forked from.

Vertica, as far as I could see, is a closed source and not based off an open source database.

So, we do see EnterpriseDB as materially different from the other examples. Note for example, that we don't include Starburst Data (based on Presto) or the Amazon Distribution of Elastic.

**Pull request closed without merging**
