### PR TITLE
`with` and `without` link is removed

### PR DESCRIPTION
**Pull request by bishal7679**
Signed-off-by: Bishal Das <70086051+bishal7679@users.noreply.github.com>

# Fixes :- #2655

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you added your SVG to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~30 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by bishal7679** [comment]
@AndreyKozlov1984 Can you review this PR?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by AndreyKozlov1984** [comment]
Hi, @bishal7679 !
Thank you for taking a look at the problem.
The real issue is that links for with and without are `https://landscape.cncf.io/?bestpractices=no` and `https://landscape.cncf.io/?bestpractices=yes`

**Comment by bishal7679** [comment]
@AndreyKozlov1984 Then I should not change that `with` and `without` link
and instead of can we add this `src/components/MainContent2.js` which is missing??

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by AndreyKozlov1984** [comment]
That src/components/MainContent2.js does not exist anymore, instead all the configuration is taken from the `settings.yml`, `big_picture` section
Regarding the with and without links - please just update the links

**Pull request closed without merging**
