### PR TITLE
landscape: add skaffold

### PR DESCRIPTION
**Pull request by r2d4**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source?
* [x] If it is open source, does your project have at least 250 GitHub stars?
* [x] Have you picked the single best category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Are you including an SVG or (less preferably) a large PNG?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] 2 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

Few comments:

* This isn't the best category for skaffold, it should probably be something more along the lines of local development/CI, but I'm fine with grouping it in this existing category.

* We don't have an official logo yet, but theres another project in the landscape reusing the GCP logo, so I assume this is fine.

### CODE REVIEW

**Comment by dankohn** [comment]
Thanks for the PR, but we're now trying to avoid all duplicate logos (other than for Certified Kubernetes offerings), as unique ones make the static landscape far more compelling:

https://raw.githubusercontent.com/cncf/landscape/master/landscape/CloudNativeLandscape_latest.png

Could you please finalize this:

https://github.com/GoogleCloudPlatform/skaffold/issues/232#issuecomment-380139267

Alternatively, we're happy to create a logo for you like https://landscape.cncf.io/selected=aws-chalice but it's not my recommendation.

**Comment by r2d4** [comment]
That makes sense. Whats the process for the alternative logo creation? I'm a little hesitant about accepting the logo from that PR since I'm not sure how it will scale for smaller image sizes.

**Comment by dankohn** [comment]
Feel free to use this, if you want, until you have a logo you're happy with.

google-cloud-scaffold

[google-cloud-scaffold.svg.zip](https://github.com/cncf/landscape/files/1900634/google-cloud-scaffold.svg.zip)

**Comment by r2d4** [comment]
This LGTM. Thanks for that awesome temporary logo, it looks much better on the CNCF landscape page. We'll prioritize getting a permanent logo finalized on our side.

**Comment by dankohn** [comment]
Great. Just open a PR when you're ready to replace the logo and/or if you create a homepage for the project.

**Comment by r2d4** [comment]
Thanks! Will do.

**Comment by nilfanif** [comment]
here is the logo i proposed a while ago. 
[Skaffold logo SVG.zip](https://github.com/cncf/landscape/files/1904649/Skaffold.logo.SVG.zip)

image

**Pull request merged**
