### PR TITLE
DO NOT MERGE YET - 801 full screen, close #801

### LINKED ISSUE #801: Full screen mode
Please add a full-screen icon just to the right of serverless. Clicking it should hide the title bar and nav bar. Here's the kind of icon to use: https://www.google.com/search?q=full+screen+icon&tbm=isch

You then need to add the inverse to restore.

### PR DESCRIPTION
**Pull request by ZeusTheTrueGod**
@dankohn , please check
- do we need a fullscreen url support ?
- mobile is not supported, the button is hidden
- in a card mode, the button is hidden too and a fullscreen mode is disabled

### CODE REVIEW

**Comment by dankohn** [comment]
Yes, please add `fullscreen=yes` to the URL in fullscreen mode. And please implement an icon for fullscreen instead of text.

Can we support on mobile?

**Comment by ZeusTheTrueGod** [comment]
I think everything is already optimised a lot for mobile devices, we even do not have a place for a text and an icon. I think what we have on a mobile is already a fullscreen mode.

**Comment by ZeusTheTrueGod** [comment]
@dankohn , I've changed an icon. I'll update you when I add a fullscreen=yes url, although it is possible just to add a `fullscreen` url without any value

**Comment by dankohn** [comment]
Icon looks good. Could you please test if you can make it work in mobile.

**Comment by ZeusTheTrueGod** [comment]
Just that is what we already have on iPhone X:
image

image

How would you optimise the available space even more?

**Comment by dankohn** [comment]
I believe all of our URL parameters are always assigned a value so can we please do so here for consistency.

**Pull request merged**
