### PR TITLE
Add Cloud Scale to CNCF Landscape list

### PR DESCRIPTION
**Pull request by nandita-cloudscaleinc**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [X] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [X] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [X] Have you picked the single best (existing) category for your project?
* [X] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [X] Have you added your SVG to `hosted_logos` and referenced it there?
* [X] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [X] Does your project/product name match the text on the logo?
* [X] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [X] ~30 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by nandita-cloudscaleinc** [comment]
LGTM

**Comment by nandita-cloudscaleinc** [comment]
LGTM 
can someone pls review. Thanks

**Comment by caniszczyk** [comment]
@taylorwaggoner is CloudScale a KCSP?

**Comment by taylorwaggoner** [comment]
@nandita-cloudscaleinc - the KCSP program requires an application and has [a few requirements](https://www.cncf.io/certification/kcsp/) your company would need to meet first, such as being a CNCF member company.  Are you interested in becoming a member and KCSP?

In the meantime, please remove the KCSP lines from your PR.  Thanks!

**Comment by nandita-cloudscaleinc** [comment]
> @nandita-cloudscaleinc - the KCSP program requires an application and has [a few requirements](https://www.cncf.io/certification/kcsp/) your company would need to meet first, such as being a CNCF member company. Are you interested in becoming a member and KCSP?
> 
> In the meantime, please remove the KCSP lines from your PR. Thanks!

Thanks @taylorwaggoner for sharing details about KCSP. To answer - As of Today we are actively providing consulting and operational support for K8s and we are looking forward to be KCSP (for that I'll follow steps that are mentioned in shared link). Meanwhile I have updated PR . Thanks !

**Comment by caniszczyk** [comment]
@taylorwaggoner are they also a certified kubernetes distro?

**Comment by taylorwaggoner** [comment]
@nandita-cloudscaleinc apologies, I missed that you had also put your company in our Certified Hosted Platform section.  This is also a section that is just for companies that have passed our [Kubernetes conformance certification process](https://www.cncf.io/certification/software-conformance/).  Once you [become a member](https://www.cncf.io/about/join/), you will be eligible to participate, if you meet the requirements. Unless your company fits into one of the other areas of the landscape, I would suggest you close this PR for now and we can reassess after you join the foundation. thank you!

**Comment by caniszczyk** [comment]
closing for now until CloudScale joins as a member: cncf.io/join

**Pull request closed without merging**
