### PR TITLE
adds northflank to ci/cd category

### PR DESCRIPTION
**Pull request by tdjsnelling**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you added your SVG to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~30 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by tdjsnelling** [comment]
Hm, fatal error:

```
2:24:48 PM: FATAL ERROR: layout issues. On a / page, following section(s) has their items out of bounds:
2:24:48 PM: [
2:24:48 PM:   'App Definition and Development\n' +
2:24:48 PM:     'Database\n' +
2:24:48 PM:     'CNCF Graduated\n' +
2:24:48 PM:     'CNCF Graduated\n' +
2:24:48 PM:     'Streaming & Messaging\n' +
2:24:48 PM:     'CNCF Incubating\n' +
2:24:48 PM:     'CNCF Incubating\n' +
2:24:48 PM:     'Application Definition & Image Build\n' +
2:24:48 PM:     'CNCF Graduated\n' +
2:24:48 PM:     'CNCF Incubating\n' +
2:24:48 PM:     'CNCF Incubating\n' +
2:24:48 PM:     'CNCF Incubating\n' +
2:24:48 PM:     'CNCF Incubating\n' +
2:24:48 PM:     'CNCF Incubating\n' +
2:24:48 PM:     'Continuous Integration & Delivery\n' +
2:24:48 PM:     'CNCF Graduated\n' +
2:24:48 PM:     'CNCF Graduated\n' +
2:24:48 PM:     'CNCF Incubating\n' +
2:24:48 PM:     'CNCF Incubating'
2:24:48 PM: ]
```

Is there anything I need to do?

**Comment by tdjsnelling** [comment]
LGTM

**Comment by tdjsnelling** [comment]
Hey @castrojo 

Anything more I need to do to get this merged? Thanks in advance.

**Comment by castrojo** [comment]
Gotcha sorry it took so long!

**Pull request merged**
